api_platform:
    title: Todo Api
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json:
            mime_types: ['application/json']
    mapping:
        paths:
            - '%kernel.project_dir%/config/api/resources'

